from selenium.webdriver.common.by import By
url="http://www.tpshop3.0tp5.com/"
login_link=By.PARTIAL_LINK_TEXT,"登录"
login_username=By.CSS_SELECTOR,"#username"
login_pwd=By.CSS_SELECTOR,"#password"
login_verify_code=By.CSS_SELECTOR,"#verify_code"
login_btn=By.CSS_SELECTOR,".J-login-submit"
login_err_info=By.CSS_SELECTOR,".layui-layer-content"
login_err_btn_ok=By.CSS_SELECTOR,".layui-layer-btn0"
logout=By.PARTIAL_LINK_TEXT,"安全退出"
login_my_shop=By.XPATH,"/html/body/div[3]/div/div[1]/a"

home=By.CSS_SELECTOR,".home"
search_input_box=By.CSS_SELECTOR,"#q"
search_Price_filter=By.CSS_SELECTOR,".brand-section"
search_search=By.CSS_SELECTOR,".ecsc-search-button"
search_Product_details=By.CSS_SELECTOR,".lazy-list"
search_add_car=By.CSS_SELECTOR,".addcar"
search_addcar_close=By.CSS_SELECTOR,".layui-layer-close"
search_addcar_success=By.XPATH,"/html/body/div/div/div/table/tbody/tr[1]/td/div/div/div[1]/div/span"
search_err=By.XPATH,"/html/body/div[4]/div/div[2]/div[2]/ul/p"
search_err2=By.XPATH,"/html/body/div[2]/div/div[2]/div[1]/span"
search_iframe_id="layui-layer-iframe1"

order_mycar=By.CSS_SELECTOR,"#hd-my-cart"
# order_all=By.CSS_SELECTOR,".checkFull"
order_paytotal=By.XPATH,"/html/body/div[2]/div[1]/div[2]/div/div/div/div/div[3]/a[2]"
order_add_address=By.PARTIAL_LINK_TEXT,"使用新地址"
order_recipient=By.XPATH,"/html/body/div/div/div/form/table/tbody/tr[1]/td[2]/input"
order_tel=By.CSS_SELECTOR,"[name='mobile']"
order_address_Province=By.CSS_SELECTOR,"#province"
order_address_city=By.CSS_SELECTOR,"#city"
order_address_district=By.CSS_SELECTOR,"#district"
order_address_detail=By.CSS_SELECTOR,"[name='address']"
order_postal_code=By.CSS_SELECTOR,"[name='zipcode']"
order_save=By.CSS_SELECTOR,"[type='submit']"
order_submit=By.CSS_SELECTOR,".Sub-orders"
order_submit_success=By.XPATH,"/html/body/div[2]/div/div[2]/div[1]/h3"
order_operation_fail=By.CSS_SELECTOR,".layui-layer-padding"
order_iframe_id="layui-layer-iframe1"
order_go_home=By.XPATH,"/html/body/div[2]/div/div[1]/div/div[1]/div/a/img"
order_sure=By.CSS_SELECTOR,".layui-layer-btn0"
order_close_iframe=By.CSS_SELECTOR,".layui-layer-setwin"

pay_myorder=By.PARTIAL_LINK_TEXT,"我的订单"
pay_pending_payment=By.PARTIAL_LINK_TEXT,"待付款"
pay_pay_immediately=By.CSS_SELECTOR,".ps_lj"
pay_cash_on_delivery=By.CSS_SELECTOR,"[value='pay_code=cod']"
pay_confirm_the_payment_method=By.PARTIAL_LINK_TEXT,"确认支付方式"
pay_pay_success=By.XPATH,"/html/body/div[2]/div/div[2]/div[1]/h3"
pay_mouse_sky=By.CSS_SELECTOR,".my-feiniu"

register_register_link=By.PARTIAL_LINK_TEXT,"注册"
register_tel=By.CSS_SELECTOR,"#username"
register_verify_code=By.CSS_SELECTOR,"[name='verify_code']"
register_set_pwd=By.CSS_SELECTOR,"#password"
register_confirm_pwd=By.CSS_SELECTOR,"#password2"
register_reference_tel=By.CSS_SELECTOR,"[name='invite']"
register_agreement=By.CSS_SELECTOR,"[type='checkbox']"
register_register_btn=By.CSS_SELECTOR,".regbtn"
register_register_success_tip=By.CSS_SELECTOR,".layui-layer-content"
register_err_info=By.XPATH,"/html/body/div[4]/div[2]"
register_err_btn_ok=By.CSS_SELECTOR,".layui-layer-btn0"
register_email_register_link=By.PARTIAL_LINK_TEXT,"邮箱注册"